import { Inter, Syne } from "next/font/google";
import "./globals.css";
import Header from "@/src/components/Header/Header"
import SmoothScrolling from "@/src/components/SmoothScrolling/SmoothScrolling"
import CustomCursor from "@/src/hooks/CustomCursor"
// const inter = Inter({ subsets: ["latin"] });
const syne = Syne({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={syne.className}>
        {/* <CustomCursor /> */}
        <main className="main">
          <SmoothScrolling>
            <Header />
            {children}
          </SmoothScrolling>
        </main>
      </body>
    </html>
  );
}
